apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  meshConfig:
    enableTracing: true
    accessLogFile: /dev/stdout
    accessLogEncoding: TEXT
    defaultConfig:
      tracing: {}
    extensionProviders:
      - name: otel-tracing
        opentelemetry:
          service: tempo.observability.svc.cluster.local
          port: 4317
